<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class GaleriSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'id_file_picker' => null,
                'nama_file' => 'Logo-PDIN.png',
                'judul' => 'Logo PDIN',
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:18:30',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:18:30',
            ],
            [
                'id' => 3,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-woodworking-2.jpg',
                'judul' => 'Ruang Woodworking',
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:17:06',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:17:06',
            ],
            [
                'id' => 4,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-woodworking-3.jpg',
                'judul' => 'Ruang Woodworking',
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:17:06',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:17:06',
            ],
            [
                'id' => 5,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-woodworking-4.jpg',
                'judul' => 'Ruang Woodworking',
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:17:06',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:17:06',
            ],
            [
                'id' => 6,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-steelworking-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:31:55',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:31:55',
            ],
            [
                'id' => 7,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-steelworking-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:31:55',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:31:55',
            ],
            [
                'id' => 8,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-1-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:35:07',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:35:07',
            ],
            [
                'id' => 9,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-1-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:35:07',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:35:07',
            ],
            [
                'id' => 10,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-1-3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:35:07',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:35:07',
            ],
            [
                'id' => 11,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-2-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:37:21',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:37:21',
            ],
            [
                'id' => 12,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-2-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:37:21',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:37:21',
            ],
            [
                'id' => 13,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-2-3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:37:21',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:37:21',
            ],
            [
                'id' => 14,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-3-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:38:59',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:38:59',
            ],
            [
                'id' => 15,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-pameran-3-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:38:59',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:38:59',
            ],
            [
                'id' => 16,
                'id_file_picker' => null,
                'nama_file' => 'foto-alun-alun-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:40:29',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:40:29',
            ],
            [
                'id' => 17,
                'id_file_picker' => null,
                'nama_file' => 'foto-alun-alun-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:40:29',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:40:29',
            ],
            [
                'id' => 18,
                'id_file_picker' => null,
                'nama_file' => 'foto-alun-alun-3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:40:29',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:40:29',
            ],
            [
                'id' => 19,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-shopping-arcade-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:44:38',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:44:38',
            ],
            [
                'id' => 20,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-shopping-arcade-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:44:38',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:44:38',
            ],
            [
                'id' => 23,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-rapat-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:56:59',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:56:59',
            ],
            [
                'id' => 24,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-rapat-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:56:59',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:56:59',
            ],
            [
                'id' => 28,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-rapat-2_2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:58:38',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:58:38',
            ],
            [
                'id' => 29,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-rapat-1_3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:58:57',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:58:57',
            ],
            [
                'id' => 30,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-rapat-2_3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 07:58:57',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 07:58:57',
            ],
            [
                'id' => 31,
                'id_file_picker' => null,
                'nama_file' => 'foto-roof-garden-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 11:52:22',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 11:52:22',
            ],
            [
                'id' => 32,
                'id_file_picker' => null,
                'nama_file' => 'foto-roof-garden-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 11:52:22',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 11:52:22',
            ],
            [
                'id' => 33,
                'id_file_picker' => null,
                'nama_file' => 'foto-roof-garden-3.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 11:52:22',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 11:52:22',
            ],
            [
                'id' => 34,
                'id_file_picker' => null,
                'nama_file' => 'foto-roof-garden-4.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 11:52:22',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 11:52:22',
            ],
            [
                'id' => 37,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-foto-produk-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:22:36',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:22:36',
            ],
            [
                'id' => 38,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-foto-produk-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:22:36',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:22:36',
            ],
            [
                'id' => 39,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-cetak-produk-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:24:44',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:24:44',
            ],
            [
                'id' => 40,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-cetak-produk-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:24:44',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:24:44',
            ],
            [
                'id' => 41,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-desainer-1.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:25:41',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:25:41',
            ],
            [
                'id' => 42,
                'id_file_picker' => null,
                'nama_file' => 'foto-ruang-desainer-2.jpg',
                'judul' => null,
                'kategori' => null,
                'id_admin_create' => null,
                'created_at' => '2023-05-22 12:25:41',
                'id_admin_update' => null,
                'updated_at' => '2023-05-22 12:25:41',
            ],
        ];

        // Insert data
        $this->db->table('galeri')->insertBatch($data);
    }
}
